title: <p align="center">Ashutosh Dutondkar</p>
logo: /assets/img/1705575159425.jpg
description: 
<p align="center">
  <a href="https://www.linkedin.com/in/ashu290995/">LinkedIn</a> |
  <a href="https://github.com/Ashu7">GitHub</a>
  <br>
  Software Engineer by profession.
  Enthusiastic personality with good logical, programming skills. 
  Well-versed with software development life cycle. Keen about learning new skills and computer languages. 
  I believe my strengths are that I am a Pedon who can work under a lot of stress.
  Technologies: Python, NumPy, Pandas, Git & GitHub, REST API, Odoo ERP v16.
  <br>
</p>

theme: jekyll-theme-minimal
